---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kibana-oauth-proxy
  name: kibana-oauth-proxy
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana-oauth-proxy
  template:
    metadata:
      labels:
        run: kibana-oauth-proxy
    spec:
      containers:
      - args:
        - --cookie-secure=false
        - --provider=github
        - --upstream=http://kibana.logging.svc.cluster.local:8080
        - --http-address=0.0.0.0:8080
        - --redirect-url=http://kibana.apps.ops.digital.cellc.co.za/oauth2/callback
        - --email-domain=*
        - --github-org=Cell-C-Digital
        - --pass-basic-auth=false
        - --pass-access-token=false
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie
              name: kibana-oauth-secrets
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: kibana-oauth-secrets
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: kibana-oauth-secrets
        image: a5huynh/oauth2_proxy:2.2
        name: oauth-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kibana-oauth-proxy
  name: kibana-oauth-proxy
  namespace: logging
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: kibana-oauth-proxy
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kibana.apps.ops.digital.cellc.co.za
    http:
      paths:
      - backend:
          serviceName: kibana-oauth-proxy
          servicePort: 8080
        path: / 