kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orders
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile