apiVersion: v1
kind: Service
metadata:
  name: captureorder-lb
  labels:
    app: captureorder
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: captureorder
