apiVersion: v1
kind: Service
metadata:
  name: captureorder
  labels:
    app: captureorder
spec:
  ports:
    - port: 8080
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: captureorder
