apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: ui
  selector:
    app: kibana
