apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventlistener
  labels:
    app: eventlistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventlistener
  template:
    metadata:
      labels:
        app: eventlistener
    spec:
      containers:
        - name: eventlistener
          image: torosent/rabbitmqlistenerack
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 100m
          env:
            - name: TEAMNAME
              value: paradise-pd
            - name: CHALLENGEAPPINSIGHTS_KEY
              value: helloworld
            - name: AMQPURL
              value: {{ .Values.rabbitMqUrl }}
            - name: PROCESSENDPOINT
              value: {{ .Values.processedEndpoint }}
          ports:
            - containerPort: 8080
